# Nord theme - ported from https://github.com/arcticicestudio/nord-hyper
background_opacity    0.90
foreground            #D8DEE9
background            #2E3440
selection_foreground  #3B4252
selection_background  #A3BE8C
url_color             #ebcb8b
cursor                #d8dee9

active_tab_foreground   #3B4252
active_tab_background   #A3BE8C
active_tab_font_style   bold-italic
inactive_tab_foreground #4C566A
inactive_tab_background #3B4252
inactive_tab_font_style normal

# black
color0   #3B4252
color8   #4C566A

# red
color1   #BF616A
color9   #d0878e

# green
color2   #A3BE8C
color10  #B1D196

# yellow
color3   #EBCB8B
color11  #F2E2C5

# blue
color4  #5E81AC
color12 #81A1C1

# magenta
color5   #B48EAD
color13  #C1A5BF

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #d8dee9
color15  #E5E9F0
