font_family             Fira Code Regular
font_size               12

bell_on_tab             no
cursor_blink_interval   0
disable_ligatures       never
enable_audio_bell       no
remember_window_size    no
scrollback_lines        10000
show_hyperlink_targets  yes
strip_trailing_spaces   always
tab_bar_style           powerline
tab_powerline_style     slanted
underline_hyperlinks    always
url_style               dashed

map alt+c copy_to_clipboard
map alt+v paste_from_clipboard
map alt+u scroll_page_up
map alt+d scroll_page_down
map alt+y copy_last_command_output
map alt+l open_url_with_hints

include ~/.config/kitty/kitty-nord.conf
include ~/.cache/wal/colors-kitty.conf
