plugins:
  # See https://k9scli.io/topics/plugins/
  sync-apps:
    shortCut: Shift-S
    confirm: false
    scopes:
      - apps
    description: Sync a argocd apps
    command: bash
    background: false
    args:
      - -c
      - "argocd app sync $NAME"
  raw-logs-follow:
    shortCut: Ctrl-L
    description: logs -f
    scopes:
      - po
    command: kubectl
    background: false
    args:
      - logs
      - -f
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  log-less:
    shortCut: Shift-L
    description: "logs|less"
    scopes:
      - po
    command: bash
    background: false
    args:
      - -c
      - '"$@" | less -S'
      - dummy-arg
      - kubectl
      - logs
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  log-less-deployment:
    shortCut: Shift-K
    description: "logs|less"
    scopes:
      - deployments
      - po
    command: bash
    background: false
    args:
      - -c
      - '"$@" | less -S'
      - dummy-arg
      - kubectl
      - logs
      - deployments/$NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
